bakery.settings:
  type: mapping
  label: Settings
  mapping:
    bakery_is_master:
      type: integer
    bakery_key:
      type: string
    bakery_master:
      type: string
    bakery_help_text:
      type: string
    bakery_freshness:
      type: string
    bakery_domain:
      type: string
    bakery_cookie_extension:
      type: string
    bakery_supported_fields:
      type: mapping
      mapping:
        mail:
          type: string
        name:
          type: string
